version: "3.9"

services:
  neo4j:
    restart: always
    image: neo4j:4.2.3
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./export/neo4j/data:/data
      - ./export/neo4j/var/lib/conf:/var/lib/neo4j/conf
      - ./export/neo4j/logs:/logs
      - ./export/neo4j/var/lib/noe4j/import:/var/lib/neo4j/import
      - ./export/noe4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
