# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ships.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bships.proto\x12\x05unary\"\x89\x02\n\tSpaceShip\x12#\n\talignment\x18\x01 \x02(\x0e\x32\x10.unary.Alignment\x12\x15\n\x04name\x18\x02 \x02(\t:\x07Unknown\x12 \n\nclass_ship\x18\x03 \x02(\x0e\x32\x0c.unary.Class\x12\x0e\n\x06length\x18\x04 \x02(\x02\x12\x11\n\tcrew_size\x18\x05 \x02(\x05\x12\r\n\x05\x61rmed\x18\x06 \x02(\x08\x12+\n\x08officers\x18\x07 \x03(\x0b\x32\x19.unary.SpaceShip.Officers\x1a?\n\x08Officers\x12\x12\n\nfirst_name\x18\x01 \x02(\t\x12\x11\n\tlast_name\x18\x02 \x02(\t\x12\x0c\n\x04rank\x18\x03 \x02(\t\"i\n\x07Message\x12\x0e\n\x06\x63ord_1\x18\x01 \x02(\x05\x12\x0e\n\x06\x63ord_2\x18\x02 \x02(\x05\x12\x0e\n\x06\x63ord_3\x18\x03 \x02(\x02\x12\x0e\n\x06\x63ord_4\x18\x04 \x02(\x05\x12\x0e\n\x06\x63ord_5\x18\x05 \x02(\x05\x12\x0e\n\x06\x63ord_6\x18\x06 \x02(\x02* \n\tAlignment\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01*\\\n\x05\x43lass\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05\x32\x42\n\x05Unary\x12\x39\n\x11GetServerResponse\x12\x0e.unary.Message\x1a\x10.unary.SpaceShip\"\x00\x30\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ships_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALIGNMENT._serialized_start=397
  _ALIGNMENT._serialized_end=429
  _CLASS._serialized_start=431
  _CLASS._serialized_end=523
  _SPACESHIP._serialized_start=23
  _SPACESHIP._serialized_end=288
  _SPACESHIP_OFFICERS._serialized_start=225
  _SPACESHIP_OFFICERS._serialized_end=288
  _MESSAGE._serialized_start=290
  _MESSAGE._serialized_end=395
  _UNARY._serialized_start=525
  _UNARY._serialized_end=591
# @@protoc_insertion_point(module_scope)
